server:
  port: 9090
spring:
  profiles:
    active: dev
    include: console-logging, file-info-logging, file-error-logging

---
spring:
  profiles: dev

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/toyProjectDB?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234
